{
    "midi_fname": "sample_music/effrhy_131.mid",
    "audio_fname": "sample_music/effrhy_131.mp3",
    "video_fname": "output/effrhy_131_settings2.mp4",
    "shadow_gradients": True,
    "shadow_positions": [
        (3, -3),
        (6, -6),
        (9, -9),
        (12, -12),
        (15, -15),
        (18, -18),
    ],
    "bg_colors": [(0, 0, 0),],
    "global_shadow_color": (0, 0, 0),
    "con_line_offset_color": (0, 0, 0),
    "con_line_offset_prop": 0.4,
    "max_connection_line_duration": 1,
    "shadow_scale": 0.95,
}
