{
    "midi_fname": "sample_music/effrhy_131.mid",
    "audio_fname": "sample_music/effrhy_131.mp3",
    "video_fname": "effrhy_131_settings2.mp4",
    "shadow_gradients": True,
    # "shadow_positions": [
    #     (3, -3),
    #     (6, -6),
    #     (9, -9),
    #     (12, -12),
    #     (15, -15),
    #     (18, -18),
    # ],
    # This looks quite cool with widely spaced shadows like
    "shadow_positions": [(3, -25), (6, -50), (9, -75),],
    "bg_colors": [(0, 0, 0),],
    "shadow_color": (0, 0, 0),
    "con_line_offset_color": (0, 0, 0),
    "con_line_offset_prop": 0.4,
    "max_connection_line_duration": 1,
    "connection_line_start_offset": 0.1,
    "connection_line_end_offset": 0.1,
    "shadow_scale": 0.95,
    "end_time": 2,
}
